README.md

Used for overriding logic & response in a Sandbox environment
https://github.com/danrevah/SandboxBundle

[Suggestion] Add SandboxBundle 

---

README.md

Raise a warning on install/update :"Package fg/essence is abandoned, you should avoid using it. Use essence/essence instead."
If you have an up-to-date bundle, I'd be grateful !

Added KayueEssenceBundle

---

README.md

- Add [SwmMailHookBundle](https://github.com/ScullWM/MailHookBundle/)
- Remove duplicate line [timeline-bundle](https://github.com/stephpy/timelinebundle)

Add bundle and remove duplicate line

---

README.md

There is one more notable Symfony FB group to be mentioned in this list. This patch adds it as well.

Second largest Symfony Facebook group to the community section

---

README.md

Add https://github.com/MWSimple/AdminCrudBundle

Add https://github.com/MWSimple/AdminCrudBundle

---

README.md

and correct ponctuation & style

Add Victoire DCMS in Distributions

---

README.md

* Add AsseticInjectorBundle
* Add MangoPayBundle
* Add AvAlertifyBundle
* Add AviaryBundle
* Add AvListBundle

Adding various Appventus Bundles

---

README.md

Twigfiddle is a small development environment to develop, run, store and access Twig code online. Might be useful to have this on this list as well.

Twigfiddle

---

README.md

Bernard makes it super easy and enjoyable to do background processing in PHP. It does this by utilizing queues and long running processes. It supports normal queueing drivers but also implements simple ones with Redis and Doctrine.

added bernard bundle

---

README.md

* Added Elcodi, a set of Symfony Bundles and PHP Components
* Added Bamboo, a full-stack E-commerce application based on Symfony and Elcodi components

Added E-commerce section in the list

---

README.md

The [KnpUGuardBundle](https://github.com/knpuniversity/KnpUGuardBundle) allow you to add simple and beautiful authentication to your Symfony project.

Add KnpUGuardBundle to the User Management list

---

README.md

AccessibleBundle provides an Accessible integration for your Symfony projects. This will allow you to define your classes getters, setters and constructors using powerful annotations.

Add AccessibleBundle to the Development list

---

README.md

Proposition of two bundles

---

README.md

Add https://github.com/csarrazi/CsaGuzzleBundle
The best Guzzle bundle out yet!

Add CsaGuzzleBundle

---

README.md

Add https://github.com/coopTilleuls/CoopTilleulsOvhBundle

Add CoopTilleulsOvhBundle

---

README.md

Add https://github.com/dunglas/DunglasAngularCsrfBundle

Add DunglasAngularCsrfBundle

---

README.md

Add https://github.com/dunglas/DunglasActionBundle

Add DunglasActionBundle

---

.travis.yml
README.md

Closes https://github.com/sitepoint/awesome-symfony/issues/52
Added CI system using TravisCI and [awesome_bot](https://github.com/dkhamsing/awesome_bot).

TravisCI using awesome-bot

---

README.md

I've checked all bundles in this part and looked at:
- Last commit date
- Number of stars
- Compatibility with Symfony ~3.4 or ~4.0
All of them had serious issues. No stars, last commit > 4 years ago or only compatible with Symfony 2.x.

Removed some Distribution repos

---

README.md

Removed inactive Forms bundles

---

README.md

The bundle one is already there.

Removed a standalone library (not a Symfony bundle)

---

README.md

It's the most popular guzzle bundle with > 700 000 downloads.

Add EightPointsGuzzleBundle and Jobeet Tutorial

---

README.md

Added link to the tabler bundle.

Added TablerBundle
